name: Deploy lyrics_transcriber/frontend to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: lyrics_transcriber/frontend/package-lock.json

      - name: Clean npm cache and modules
        working-directory: lyrics_transcriber/frontend
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm cache clean --force

      - name: Install dependencies
        working-directory: lyrics_transcriber/frontend
        run: npm install

      - name: Build
        working-directory: lyrics_transcriber/frontend
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./lyrics_transcriber/frontend/dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
